DELETE http://localhost:3003/api/blogs/694962c3d0c58549a4d9c454
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGUiLCJpZCI6IjY5NDE0MWVkMjBhMTAzMzZkZTBkZGI3NiIsImlhdCI6MTc2NzY1NDAzMn0.0nGmfzueoFX6NZ6XXGhGoBVYj0f2wrfB0wPj2xBBOqc
